import { expect, test, type Page } from "@playwright/test";

import { readSmokeInfo, repoHome, type SmokeInfo } from "../fixtures";

/**
 * The product surfaces, browsed with a real session against real data.
 *
 * Strictly read-only: nothing here writes. Re-ingest in particular is off limits -- it
 * deletes and recreates the repository row and cascades away every file, symbol and guide
 * under it, which is why the local suite gives that path a repository of its own.
 *
 * Nothing asserts on the *content* of the analysis, because it is generated by a model and
 * differs run to run. What is asserted is that each surface renders and is reachable.
 *
 * Both are resolved in `beforeEach`, not at module scope: Playwright loads every spec file
 * to build its test list before any project runs, so reading the setup artifact here would
 * throw during collection and take the whole run down.
 */

let info: SmokeInfo;
let home: string;

test.beforeEach(() => {
  info = readSmokeInfo();
  home = repoHome(info);
});

/**
 * Waits for the repository route to finish streaming.
 *
 * `loading.tsx` renders a skeleton carrying the same "Processing Status" label as the real
 * page, so mid-stream a bare locator for that text matches two elements and Playwright
 * raises a strict-mode violation. A count of one is the settled state.
 */
async function settle(page: Page) {
  await expect(page.getByText("Processing Status")).toHaveCount(1);
}

/** Counts the distinct colours the compositor actually put on the canvas. */
async function distinctCanvasColours(page: Page) {
  const canvas = page.locator("canvas").first();
  await expect(canvas).toBeVisible();

  const shot = await canvas.screenshot();

  return page.evaluate(async (base64) => {
    const response = await fetch(`data:image/png;base64,${base64}`);
    const bitmap = await createImageBitmap(await response.blob());
    const offscreen = new OffscreenCanvas(bitmap.width, bitmap.height);
    const context = offscreen.getContext("2d")!;
    context.drawImage(bitmap, 0, 0);

    const { data } = context.getImageData(0, 0, bitmap.width, bitmap.height);
    const seen = new Set<string>();
    for (let i = 0; i < data.length; i += 4) {
      seen.add(`${data[i]},${data[i + 1]},${data[i + 2]}`);
    }
    return seen.size;
  }, shot.toString("base64"));
}

test.describe("the dashboard", () => {
  test("keeps the browser on the dashboard rather than bouncing to login", async ({ page }) => {
    // The single highest-value assertion in this file. Reaching /dashboard with a stored
    // cookie requires the cookie to be scoped to the registrable domain, to be sent by the
    // browser on a request to the *web* origin, and to be visible to the Next proxy there.
    // When DOMAIN is host-only this is the test that says so.
    await page.goto("/dashboard");

    await expect(page).toHaveURL(/\/dashboard/);
    await expect(page.getByText(/Application error/i)).toHaveCount(0);
  });

  test("lists the smoke repository as ready, and opens it", async ({ page }) => {
    await page.goto("/dashboard");

    const card = page.getByRole("link", { name: info.repo.name });
    await expect(card).toBeVisible();
    // `ready` is the gate on the graph endpoint and on the repository page rendering its
    // guide instead of a log stream, so it is worth pinning rather than assuming.
    await expect(card.getByText("ready", { exact: true })).toBeVisible();

    // Clicked rather than navigated to by URL, so the link the dashboard actually renders
    // is exercised. Every other spec navigates directly, which would never touch a broken
    // href -- this is the one place the rendered link is the thing under test.
    await card.click();
    await expect(page).toHaveURL(new RegExp(`${home}$`));
  });
});

test.describe("the repository overview", () => {
  test("renders without error", async ({ page }) => {
    const response = await page.goto(home);

    expect(response?.status()).toBe(200);
    await settle(page);
    await expect(page.getByText(/Application error/i)).toHaveCount(0);
    await expect(page.getByText("AI Architecture Overview")).toBeVisible();
  });

  test("renders the chat panel", async ({ page }) => {
    await page.goto(home);

    await expect(page.getByRole("heading", { name: /Chat with Codebase/i })).toBeVisible();
  });
});

test.describe("the explorer and the glossary", () => {
  test("renders the file tree", async ({ page }) => {
    await page.goto(`${home}/explorer`);

    await expect(page.getByRole("heading", { name: "File Explorer" })).toBeVisible();
  });

  test("lists glossary entries", async ({ page }) => {
    await page.goto(`${home}/glossary`);

    // The count, not a term: the glossary is model-generated, so a specific entry is not
    // something this suite can rely on. An empty list renders no count at all.
    await expect(page.getByText(/Showing \d+ of \d+ entries/)).toBeVisible();
  });
});

test.describe("the dependency graph", () => {
  test("paints the canvas", async ({ page }) => {
    // This is also the WebGL check for the whole suite. The graph is a real three.js scene
    // on a headless runner with no GPU, so it only draws at all because of the SwiftShader
    // flags in the config -- if those regress, this is the test that says so.
    //
    // A blank or unrendered canvas is one or two colours; a force graph with antialiased
    // nodes, links and text is in the hundreds.
    await page.goto(`${home}/graph`);
    await expect(page.getByText(/Size ∝ LOC/)).toBeVisible();

    expect(await distinctCanvasColours(page)).toBeGreaterThan(50);
  });

  test("switches between file and symbol level", async ({ page }) => {
    await page.goto(`${home}/graph`);

    await page.getByRole("button", { name: "Symbol Level" }).click();

    // The level is a route query, so the assertion is that the navigation happened and the
    // page came back rather than erroring.
    await expect(page).toHaveURL(/level=symbol/);
    await expect(page.getByText(/Application error/i)).toHaveCount(0);
  });
});

test.describe("the settings route", () => {
  test("renders the credentials editor", async ({ page }) => {
    const response = await page.goto("/settings");

    expect(response?.status()).toBe(200);
    await expect(page.getByRole("heading", { name: "Settings" })).toBeVisible();
  });
});
