"""Alembic revision chain and schema drift.

Three separate concerns, and the third is the one that has actually caught defects in
this repository:

* the chain is well-formed (one head, no branches, no dangling parents),
* the database is at that head,
* the models and the migrated schema still agree.
"""

from datetime import UTC

import pytest
from alembic.autogenerate import compare_metadata
from alembic.migration import MigrationContext
from alembic.runtime.migration import MigrationContext as RuntimeContext
from sqlalchemy import create_engine

from tests.conftest import TEST_SYNC_DB_URL

pytestmark = pytest.mark.migration


def head_revision(alembic_config) -> str:
    """
    The single revision `upgrade head` would land on.

    Asserts rather than returning `str | None`: a head of `None` means the revision chain
    is broken, which is one of the things this module exists to catch, so it should fail
    here with that message rather than as an obscure comparison later.
    """
    from alembic.script import ScriptDirectory

    head = ScriptDirectory.from_config(alembic_config).get_current_head()
    assert head is not None, "the migration chain has no head"
    return head


def applied_revision() -> str | None:
    """The revision the test database currently records."""
    engine = create_engine(TEST_SYNC_DB_URL)
    try:
        with engine.connect() as connection:
            return RuntimeContext.configure(connection).get_current_revision()
    finally:
        engine.dispose()


class TestRevisionChain:
    def test_there_is_exactly_one_head(self, alembic_config):
        """
        Two heads mean two divergent branches, and `upgrade head` then refuses to run.
        """
        from alembic.script import ScriptDirectory

        assert len(ScriptDirectory.from_config(alembic_config).get_heads()) == 1

    def test_the_chain_is_linear(self, alembic_config):
        """
        A revision with two children is a branch point. Linear history keeps
        `downgrade -1` meaningful and makes review of a migration readable.
        """
        from alembic.script import ScriptDirectory

        branched = [
            revision.revision
            for revision in ScriptDirectory.from_config(alembic_config).walk_revisions()
            if len(revision.nextrev) > 1
        ]

        assert branched == []

    def test_every_revision_is_reachable_from_the_head(self, alembic_config):
        """
        `walk_revisions` starts at the head and follows parents. A revision that cannot
        be reached is an orphan -- usually a leftover from a deleted file.
        """
        from alembic.script import ScriptDirectory

        script = ScriptDirectory.from_config(alembic_config)
        reachable = {revision.revision for revision in script.walk_revisions()}
        on_disk = {
            revision.revision for revision in script.walk_revisions(base="base", head="heads")
        }

        assert reachable == on_disk

    def test_no_revision_is_an_empty_no_op(self, alembic_config):
        """
        An autogenerated revision whose body was never written still occupies a slot in
        the chain and silently skips a schema change. Three of them were removed from
        this chain, including the one meant to convert `repo_number` into an identity
        column -- its emptiness is why repository creation failed against every database
        built from these migrations.

        The assertion is deliberately the invariant rather than any named revision: every
        `upgrade` body must contain at least one `op.` call, so the next empty revision
        fails here instead of reaching a database.
        """
        import re
        from pathlib import Path

        from alembic.script import ScriptDirectory

        script = ScriptDirectory.from_config(alembic_config)
        empty: list[str] = []
        for revision in script.walk_revisions():
            path = Path(revision.path)
            if path.suffix != ".py":
                continue
            body = path.read_text(encoding="utf-8")
            upgrade = body.split("def upgrade", 1)[-1].split("def downgrade", 1)[0]
            # Strip the docstring and comments; anything left is real work.
            stripped = re.sub(r'"""[\s\S]*?"""', "", upgrade)
            stripped = "\n".join(
                line for line in stripped.splitlines() if not line.strip().startswith("#")
            )
            if not re.search(r"\bop\.", stripped):
                empty.append(revision.revision)

        assert empty == [], f"These revisions contain no `op.` calls and change nothing: {empty}"


class TestDatabaseIsAtHead:
    def test_applied_revision_matches_the_head(self, alembic_config):
        assert applied_revision() == head_revision(alembic_config)

    def test_upgrade_head_is_idempotent(self, alembic_config):
        """Running it twice is a no-op, which is what CI does after a cached migrate."""
        from alembic import command
        from tests.conftest import _existing_loggers_survive

        with _existing_loggers_survive():
            command.upgrade(alembic_config, "head")

        assert applied_revision() == head_revision(alembic_config)


class TestSchemaDrift:
    def test_the_models_match_the_migrated_schema(self):
        """
        The check that compares the live schema against `Base.metadata` and reports
        anything that differs -- so a model/schema mismatch surfaces here rather than in
        production. The defects it was written against were not shape changes (an empty
        migration, an enum whose model and database labels disagree), which is why it
        passes while they remain. A non-empty result means the models promise something
        the database does not provide (or the reverse), and no autogenerated migration can
        be trusted until it is reconciled.

        The one entry it currently reports is the global `UNIQUE (hash)` on `commits`,
        which the models do not declare -- `TestCommitHashUniqueness` below is where that
        entry's consequences are pinned.
        """
        assert model_schema_diff() == []

    def test_the_drift_check_actually_inspects_the_schema(self):
        """
        A control for the test above: if the diff came back empty because nothing was
        compared -- an unimported model module, a bad connection -- the assertion would
        pass for the wrong reason. Comparing against an empty MetaData must report every
        table as missing.
        """
        from sqlalchemy import MetaData

        assert model_schema_diff(MetaData()) != []


class TestCommitHashUniqueness:
    """
    The drift reported by `TestSchemaDrift` is not cosmetic -- it changes what the
    ingestion path can do.

    `git_analyzer._bulk_insert_commits` inserts with
    `ON CONFLICT (repository_id, hash) DO NOTHING`, which is exactly what the model
    declares: a commit is unique *within* a repository, so re-analysing a repo is
    idempotent while the same commit appearing in two repos is fine.

    The database additionally carries a global `UNIQUE (hash)` from
    `570a9dabb547`. `ON CONFLICT (repository_id, hash)` does not cover a conflict on that
    constraint, so it does not absorb the error.
    """

    HASH = "a" * 40

    def commit_row(self, repo_id):
        from datetime import datetime

        return {
            "repository_id": repo_id,
            "hash": self.HASH,
            "author_name": "Ada Lovelace",
            "author_email": "ada@example.com",
            "message": "feat: shared commit",
            "files_changed": 1,
            "authored_at": datetime(2026, 1, 1, tzinfo=UTC),
            "changed_files_list": ["src/a.py"],
        }

    async def insert_like_ingestion(self, db_session, rows):
        """Mirror the real insert, including its conflict target."""
        from sqlalchemy.dialects.postgresql import insert as pg_insert

        from app.models import Commit

        await db_session.execute(
            pg_insert(Commit)
            .values(rows)
            .on_conflict_do_nothing(index_elements=["repository_id", "hash"])
        )
        await db_session.flush()

    @pytest.mark.asyncio
    async def test_two_repositories_may_share_a_commit(self, db_session):
        """
        Forking a repository is the everyday case: a fork and its upstream share every
        commit up to the fork point, byte-identical hashes included. Ingestion of the
        second one must not fail.

        Today it raises `UniqueViolationError` on `commits_hash_key`, because the conflict
        is on a constraint the insert's `ON CONFLICT` target does not name -- so it
        propagates out of `analyze_git_history` and fails the whole ingestion.
        """
        from tests.factories import make_repo, make_user

        user = await make_user(db_session)
        upstream = await make_repo(db_session, user, name="upstream")
        fork = await make_repo(db_session, user, name="fork")

        await self.insert_like_ingestion(db_session, [self.commit_row(upstream.id)])
        await self.insert_like_ingestion(db_session, [self.commit_row(fork.id)])

        from sqlalchemy import select

        from app.models import Commit

        stored = await db_session.execute(select(Commit).where(Commit.hash == self.HASH))
        assert len(stored.scalars().all()) == 2

    async def test_reanalysing_the_same_repository_is_idempotent(self, db_session):
        """
        The control, and the behaviour the `ON CONFLICT` target was written for: the same
        commit twice in the *same* repository is absorbed. Note the contrast -- the
        conflict target works here and fails above, which is what makes the extra
        constraint the problem rather than the insert.
        """
        from sqlalchemy import select

        from app.models.commit import Commit
        from tests.factories import make_repo, make_user

        user = await make_user(db_session)
        repo = await make_repo(db_session, user)

        await self.insert_like_ingestion(db_session, [self.commit_row(repo.id)])
        await self.insert_like_ingestion(db_session, [self.commit_row(repo.id)])

        stored = await db_session.execute(select(Commit).where(Commit.repository_id == repo.id))
        assert len(stored.scalars().all()) == 1


class TestAutoUpdateDefaults:
    """
    ``server_default`` populates a column only on rows inserted *after* the
    column lands; existing rows are backfilled by the migration. A column that
    is NULL on a freshly-inserted row -- because nothing in the migration
    asserted ``NOT NULL`` -- breaks the sync task the next time it claims the
    repo: ``next_sync_at IS NULL AND auto_update_enabled`` is a valid filter
    shape, but ``consecutive_sync_failures`` getting NULL breaks every
    arithmetic on it.

    Each row inserted through ``make_repo`` lists every column explicitly (the
    factory was written for a smaller schema), so this is the regression test
    that catches a future migration that adds a NOT NULL column without a
    matching ``server_default`` or backfill.
    """

    async def test_make_repo_yields_a_row_with_non_null_defaults(self, db_session):
        """
        ``make_repo`` builds the row from the factory -- no field-list
        gymnastics, just the model. If the column is NOT NULL on the database
        side and ``server_default`` is set, this passes. If either is missing,
        the INSERT fails or returns a row with NULLs.
        """
        from sqlalchemy import select

        from app.models.repository import Repository
        from tests.factories import make_repo, make_user

        user = await make_user(db_session)
        repo = await make_repo(db_session, user)

        result = await db_session.execute(select(Repository).where(Repository.id == repo.id))
        stored = result.scalar_one()

        assert stored.auto_update_enabled is False
        assert stored.auto_update_interval_hours == 6
        assert stored.next_sync_at is None
        assert stored.last_synced_at is None
        assert stored.sync_status == "idle"
        assert stored.sync_lease_expires_at is None
        assert stored.sync_generation is None
        assert stored.last_sync_error is None
        assert stored.consecutive_sync_failures == 0
        assert stored.last_sync_summary is None
        assert stored.analysis_commit_sha is None

    async def test_inserting_a_row_without_the_new_columns_still_works(self, db_session):
        """
        The reingest path rebuilds ``Repository`` from an explicit field list
        -- a list that, until the migration, did not include the new columns.
        The migration must give every new column a ``server_default`` so this
        INSERT lands a valid row, not a NOT NULL violation.

        The raw INSERT mirrors that shape: an explicit column list with no
        values for the new columns. ``repo_number`` is omitted as well, so the
        database identity supplies it -- which is the point of the column
        having a generator at all.
        """
        from sqlalchemy import text

        from tests.factories import make_user

        user = await make_user(db_session)

        await db_session.execute(
            text(
                """
                INSERT INTO repositories
                    (user_id, github_url, name, status)
                VALUES
                    (:uid, 'https://github.com/example/legacy-rebuild',
                     'legacy-rebuild', 'pending')
                """
            ),
            {"uid": user.id},
        )
        await db_session.flush()

        row = (
            await db_session.execute(
                text(
                    "SELECT auto_update_enabled, auto_update_interval_hours, sync_status, "
                    "consecutive_sync_failures, next_sync_at, sync_lease_expires_at "
                    "FROM repositories WHERE name = 'legacy-rebuild'"
                )
            )
        ).one()
        assert row.auto_update_enabled is False
        assert row.auto_update_interval_hours == 6
        assert row.sync_status == "idle"
        assert row.consecutive_sync_failures == 0
        # Nullable columns stay NULL.
        assert row.next_sync_at is None
        assert row.sync_lease_expires_at is None


class TestByokAndFreeTierDefaults:
    """
    ``c3d4e5f6a7b8`` adds the BYOK credential columns and free-tier counters
    to ``users``. Two invariants must hold for the schema to be usable
    without application code reaching for ``None`` on every read:

    * the four BYOK columns are nullable -- a user with no key is the
      free-tier case, not a malformed row;
    * the two counter columns are NOT NULL with ``server_default`` so a raw
      ``INSERT`` (the reingest rebuild path that lists every column
      explicitly) still lands a usable row.

    The migration's two backfill ``UPDATE``s also live here as regression
    tests: a user with a stored key keeps ``auto_update_enabled`` (so the
    operator's free-tier key cannot opt them into auto-update), and a
    keyless user with a repository gets ``auto_update_enabled`` flipped to
    ``false`` and ``next_sync_at`` cleared.
    """

    async def test_a_freshly_inserted_user_row_has_free_tier_defaults(self, db_session):
        """``make_user`` lists every column explicitly; the new ones must still land populated."""
        from sqlalchemy import select

        from app.models.user import User
        from tests.factories import make_user

        user = await make_user(db_session)

        stored = (await db_session.execute(select(User).where(User.id == user.id))).scalar_one()

        # BYOK columns start NULL -- a user with no key is the free-tier case.
        assert stored.ai_provider is None
        assert stored.ai_api_key is None
        assert stored.ai_model is None
        assert stored.ai_key_validated_at is None
        # Free-tier counters carry their ``server_default`` values.
        assert stored.free_ingest_used is False
        assert stored.free_chat_messages_used == 0

    async def test_the_schema_has_six_columns_with_the_expected_types(self):
        """
        Query the catalog directly: the six columns must exist with the
        types and nullability the model declares. This is the schema-level
        companion to the row-level check above -- a future migration that
        drops a column or changes its type surfaces here.
        """
        from sqlalchemy import create_engine, text

        from tests.conftest import TEST_SYNC_DB_URL

        engine = create_engine(TEST_SYNC_DB_URL)
        try:
            with engine.connect() as connection:
                rows = connection.execute(
                    text(
                        """
                        SELECT column_name, data_type, is_nullable, column_default
                        FROM information_schema.columns
                        WHERE table_name = 'users'
                          AND column_name IN (
                            'ai_provider', 'ai_api_key', 'ai_model', 'ai_key_validated_at',
                            'free_ingest_used', 'free_chat_messages_used'
                          )
                        """
                    )
                ).all()
        finally:
            engine.dispose()

        by_name = {row.column_name: row for row in rows}
        assert set(by_name) == {
            "ai_provider",
            "ai_api_key",
            "ai_model",
            "ai_key_validated_at",
            "free_ingest_used",
            "free_chat_messages_used",
        }

        # BYOK columns are nullable -- a keyless user is a valid state.
        for nullable_column in ("ai_provider", "ai_api_key", "ai_model", "ai_key_validated_at"):
            assert by_name[nullable_column].is_nullable == "YES", (
                f"{nullable_column} must be nullable so a keyless user is not malformed"
            )

        # Counters are NOT NULL with server defaults so a raw INSERT lands a usable row.
        assert by_name["free_ingest_used"].is_nullable == "NO"
        assert "false" in (by_name["free_ingest_used"].column_default or "").lower()
        assert by_name["free_chat_messages_used"].is_nullable == "NO"
        assert "0" in (by_name["free_chat_messages_used"].column_default or "")


class TestByokAndFreeTierBackfill:
    """
    The migration's two ``UPDATE``s reflect a deliberate operational state
    change for existing accounts: anyone with a repository has used their
    free ingestion, and keyless users stop getting auto-update subsidised
    on the server key.

    These tests run against the migrated database and inspect what the
    backfill left behind. They construct rows that match the predicates the
    ``UPDATE``s check, so the assertions exercise the actual backfill shape
    rather than its absence.
    """

    async def test_a_user_without_a_repository_is_backfilled_as_unused(self, db_session):
        """A user with no repository has not ingested -- their counter stays at the default."""
        from sqlalchemy import select

        from app.models.user import User
        from tests.factories import make_user

        user = await make_user(db_session)

        stored = (await db_session.execute(select(User).where(User.id == user.id))).scalar_one()

        # The backfill's first UPDATE only marks users-with-a-repository. A
        # fresh user with no repos has not had the flag flipped.
        assert stored.free_ingest_used is False

    async def test_a_user_with_a_repository_is_backfilled_as_used(self, db_session):
        """A user who already owns a repo has demonstrably ingested at least once."""
        from tests.factories import make_repo, make_user

        user = await make_user(db_session)
        await make_repo(db_session, user)

        # Apply the migration's first backfill UPDATE -- the same statement
        # the migration executes, imported from the migration module so the
        # SQL cannot drift between migration and test.
        await db_session.execute(_migration_text("MARK_USERS_WITH_REPOS_AS_FREE_INGEST_USED"))
        await db_session.flush()

        # ``make_user`` put the ``User`` row in the session's identity map
        # via ``refresh``; a raw ``UPDATE`` does not invalidate it.
        # ``refresh`` re-reads the row so the assertion below observes the
        # post-backfill state rather than the snapshot the factory cached.
        await db_session.refresh(user)

        assert user.free_ingest_used is True

    async def test_a_keyless_user_with_a_repo_has_auto_update_cleared(self, db_session):
        """
        A user with no stored key cannot pay for an auto-update cycle.

        The migration flips ``auto_update_enabled`` to ``false`` and
        clears ``next_sync_at`` so the sweep's claim predicate never
        reaches the repo. Re-enabling auto-update requires the user to
        have a stored key -- the settings screen's contract.
        """
        from datetime import UTC, datetime, timedelta

        from tests.factories import make_repo, make_user

        user = await make_user(db_session)
        repo = await make_repo(
            db_session,
            user,
            # ``make_repo`` defaults ``auto_update_enabled`` to ``false``;
            # flip it back on so the backfill's effect is observable.
        )
        repo.auto_update_enabled = True
        repo.next_sync_at = datetime.now(UTC) + timedelta(hours=1)
        await db_session.flush()

        # Apply the migration's second UPDATE shape -- imported from the
        # migration module so the SQL stays in lockstep.
        await db_session.execute(_migration_text("CLEAR_AUTO_UPDATE_FOR_KEYLESS_OWNERS"))
        await db_session.flush()

        # The ``Repository`` is in the identity map from ``make_repo``; the
        # raw ``UPDATE`` does not invalidate the in-memory copy. ``refresh``
        # re-reads the row so the assertion below observes the post-backfill
        # state rather than the snapshot the factory cached.
        await db_session.refresh(repo)

        assert repo.auto_update_enabled is False
        assert repo.next_sync_at is None

    async def test_a_user_with_a_stored_key_keeps_auto_update_enabled(self, db_session):
        """
        The backfill is conditioned on ``ai_api_key IS NULL``: a user who
        has set up their own key keeps the auto-update state the
        application recorded for them.

        This is the symmetric case to the test above -- a regression that
        unconditionally clears auto-update would silently disable
        background syncing for every BYOK user.
        """
        from datetime import UTC, datetime

        from tests.factories import make_repo, make_user

        user = await make_user(db_session)
        user.ai_provider = "openai"
        user.ai_api_key = "sk-test"
        user.ai_model = "gpt-4o-mini"
        user.ai_key_validated_at = datetime.now(UTC)
        await db_session.flush()

        repo = await make_repo(db_session, user)
        repo.auto_update_enabled = True
        await db_session.flush()

        # Apply the migration's second UPDATE shape. Because ``ai_api_key``
        # is populated, the WHERE clause that selects rows to clear does
        # not match this user's repositories.
        await db_session.execute(_migration_text("CLEAR_AUTO_UPDATE_FOR_KEYLESS_OWNERS"))
        await db_session.flush()

        # ``make_user`` / ``make_repo`` put both rows in the identity map;
        # the raw ``UPDATE`` does not invalidate them. Refresh both so the
        # assertions observe the post-backfill state.
        await db_session.refresh(user)
        await db_session.refresh(repo)

        assert user.ai_api_key == "sk-test"
        assert repo.auto_update_enabled is True


def _migration_text(name: str):
    """Load the named module-level SQL constant from the BYOK / free-tier migration.

    The migration file lives under ``alembic/versions/``, which has no
    ``__init__.py`` so it is not a Python package -- a plain
    ``from alembic.versions.X`` would not resolve. Loading the file by
    path keeps the migration's SQL as the single source of truth while
    still letting the test reference it.
    """
    import importlib.util
    from pathlib import Path

    from sqlalchemy import text

    path = (
        Path(__file__).resolve().parents[2]
        / "alembic"
        / "versions"
        / "c3d4e5f6a7b8_add_byok_and_free_tier.py"
    )
    spec = importlib.util.spec_from_file_location("_byok_free_tier_migration", path)
    assert spec is not None and spec.loader is not None, (
        f"failed to load migration module from {path}"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return text(getattr(module, name))


def model_schema_diff(metadata=None) -> list:
    """
    Compare the migrated database against the ORM metadata.

    `app.models` is imported for its side effect of registering every mapper; without it
    the metadata would be incomplete and the comparison would report most of the schema
    as "to be removed".
    """
    import app.models  # noqa: F401
    from app.core.database import Base

    engine = create_engine(TEST_SYNC_DB_URL)
    try:
        with engine.connect() as connection:
            context = MigrationContext.configure(connection, opts={"compare_type": True})
            return compare_metadata(context, metadata if metadata is not None else Base.metadata)
    finally:
        engine.dispose()
