"""Alembic revision chain and schema drift.

Three separate concerns, and the third is the one that has actually caught defects in
this repository:

* the chain is well-formed (one head, no branches, no dangling parents),
* the database is at that head,
* the models and the migrated schema still agree.
"""

from datetime import UTC

import pytest
from alembic.autogenerate import compare_metadata
from alembic.migration import MigrationContext
from alembic.runtime.migration import MigrationContext as RuntimeContext
from sqlalchemy import create_engine

from tests.conftest import TEST_SYNC_DB_URL
from tests.helpers import EMPTY_MIGRATIONS

pytestmark = pytest.mark.migration


def head_revision(alembic_config) -> str:
    """
    The single revision `upgrade head` would land on.

    Asserts rather than returning `str | None`: a head of `None` means the revision chain
    is broken, which is one of the things this module exists to catch, so it should fail
    here with that message rather than as an obscure comparison later.
    """
    from alembic.script import ScriptDirectory

    head = ScriptDirectory.from_config(alembic_config).get_current_head()
    assert head is not None, "the migration chain has no head"
    return head


def applied_revision() -> str | None:
    """The revision the test database currently records."""
    engine = create_engine(TEST_SYNC_DB_URL)
    try:
        with engine.connect() as connection:
            return RuntimeContext.configure(connection).get_current_revision()
    finally:
        engine.dispose()


class TestRevisionChain:
    def test_there_is_exactly_one_head(self, alembic_config):
        """
        Two heads mean two divergent branches, and `upgrade head` then refuses to run.
        """
        from alembic.script import ScriptDirectory

        assert len(ScriptDirectory.from_config(alembic_config).get_heads()) == 1

    def test_the_chain_is_linear(self, alembic_config):
        """
        A revision with two children is a branch point. Linear history keeps
        `downgrade -1` meaningful and makes review of a migration readable.
        """
        from alembic.script import ScriptDirectory

        branched = [
            revision.revision
            for revision in ScriptDirectory.from_config(alembic_config).walk_revisions()
            if len(revision.nextrev) > 1
        ]

        assert branched == []

    def test_every_revision_is_reachable_from_the_head(self, alembic_config):
        """
        `walk_revisions` starts at the head and follows parents. A revision that cannot
        be reached is an orphan -- usually a leftover from a deleted file.
        """
        from alembic.script import ScriptDirectory

        script = ScriptDirectory.from_config(alembic_config)
        reachable = {revision.revision for revision in script.walk_revisions()}
        on_disk = {
            revision.revision for revision in script.walk_revisions(base="base", head="heads")
        }

        assert reachable == on_disk

    @EMPTY_MIGRATIONS
    def test_no_revision_is_an_empty_no_op(self, alembic_config):
        """
        An autogenerated revision whose body was never written still occupies a slot in
        the chain and silently skips a schema change. `1bae111890c6` did exactly that --
        `repo_number` was never converted to an identity because the migration that was
        supposed to do it is empty.

        Three revisions are currently empty. Two are merely redundant:

        * `95fdf3002015` (`initial_schema`) -- superseded scaffolding.
        * `1882dcee3456` (`add_file_source_type_in_embeddings`) -- checked directly: the
          `embeddings.source_type` column does exist, created by another revision, so
          nothing is missing.

        Only `1bae111890c6` is load-bearing, and filling it in is what would fix the
        missing generator.
        """
        import re
        from pathlib import Path

        from alembic.script import ScriptDirectory

        script = ScriptDirectory.from_config(alembic_config)
        empty: list[str] = []
        for revision in script.walk_revisions():
            path = Path(revision.path)
            if path.suffix != ".py":
                continue
            body = path.read_text(encoding="utf-8")
            upgrade = body.split("def upgrade", 1)[-1].split("def downgrade", 1)[0]
            # Strip the docstring and comments; anything left is real work.
            stripped = re.sub(r'"""[\s\S]*?"""', "", upgrade)
            stripped = "\n".join(
                line for line in stripped.splitlines() if not line.strip().startswith("#")
            )
            if not re.search(r"\bop\.", stripped):
                empty.append(revision.revision)

        assert empty == [], f"These revisions contain no `op.` calls and change nothing: {empty}"


class TestDatabaseIsAtHead:
    def test_applied_revision_matches_the_head(self, alembic_config):
        assert applied_revision() == head_revision(alembic_config)

    def test_upgrade_head_is_idempotent(self, alembic_config):
        """Running it twice is a no-op, which is what CI does after a cached migrate."""
        from alembic import command
        from tests.conftest import _existing_loggers_survive

        with _existing_loggers_survive():
            command.upgrade(alembic_config, "head")

        assert applied_revision() == head_revision(alembic_config)


class TestSchemaDrift:
    def test_the_models_match_the_migrated_schema(self):
        """
        The check that compares the live schema against `Base.metadata` and reports
        anything that differs -- so a model/schema mismatch surfaces here rather than in
        production. The defects it was written against were not shape changes (an empty
        migration, an enum whose model and database labels disagree), which is why it
        passes while they remain. A non-empty result means the models promise something
        the database does not provide (or the reverse), and no autogenerated migration can
        be trusted until it is reconciled.

        The one entry it currently reports is the global `UNIQUE (hash)` on `commits`,
        which the models do not declare -- `TestCommitHashUniqueness` below is where that
        entry's consequences are pinned.
        """
        assert model_schema_diff() == []

    def test_the_drift_check_actually_inspects_the_schema(self):
        """
        A control for the test above: if the diff came back empty because nothing was
        compared -- an unimported model module, a bad connection -- the assertion would
        pass for the wrong reason. Comparing against an empty MetaData must report every
        table as missing.
        """
        from sqlalchemy import MetaData

        assert model_schema_diff(MetaData()) != []


class TestCommitHashUniqueness:
    """
    The drift reported by `TestSchemaDrift` is not cosmetic -- it changes what the
    ingestion path can do.

    `git_analyzer._bulk_insert_commits` inserts with
    `ON CONFLICT (repository_id, hash) DO NOTHING`, which is exactly what the model
    declares: a commit is unique *within* a repository, so re-analysing a repo is
    idempotent while the same commit appearing in two repos is fine.

    The database additionally carries a global `UNIQUE (hash)` from
    `570a9dabb547`. `ON CONFLICT (repository_id, hash)` does not cover a conflict on that
    constraint, so it does not absorb the error.
    """

    HASH = "a" * 40

    def commit_row(self, repo_id):
        from datetime import datetime

        return {
            "repository_id": repo_id,
            "hash": self.HASH,
            "author_name": "Ada Lovelace",
            "author_email": "ada@example.com",
            "message": "feat: shared commit",
            "files_changed": 1,
            "authored_at": datetime(2026, 1, 1, tzinfo=UTC),
            "changed_files_list": ["src/a.py"],
        }

    async def insert_like_ingestion(self, db_session, rows):
        """Mirror the real insert, including its conflict target."""
        from sqlalchemy.dialects.postgresql import insert as pg_insert

        from app.models import Commit

        await db_session.execute(
            pg_insert(Commit)
            .values(rows)
            .on_conflict_do_nothing(index_elements=["repository_id", "hash"])
        )
        await db_session.flush()

    @pytest.mark.asyncio
    async def test_two_repositories_may_share_a_commit(self, db_session):
        """
        Forking a repository is the everyday case: a fork and its upstream share every
        commit up to the fork point, byte-identical hashes included. Ingestion of the
        second one must not fail.

        Today it raises `UniqueViolationError` on `commits_hash_key`, because the conflict
        is on a constraint the insert's `ON CONFLICT` target does not name -- so it
        propagates out of `analyze_git_history` and fails the whole ingestion.
        """
        from tests.factories import make_repo, make_user

        user = await make_user(db_session)
        upstream = await make_repo(db_session, user, name="upstream")
        fork = await make_repo(db_session, user, name="fork")

        await self.insert_like_ingestion(db_session, [self.commit_row(upstream.id)])
        await self.insert_like_ingestion(db_session, [self.commit_row(fork.id)])

        from sqlalchemy import select

        from app.models import Commit

        stored = await db_session.execute(select(Commit).where(Commit.hash == self.HASH))
        assert len(stored.scalars().all()) == 2

    async def test_reanalysing_the_same_repository_is_idempotent(self, db_session):
        """
        The control, and the behaviour the `ON CONFLICT` target was written for: the same
        commit twice in the *same* repository is absorbed. Note the contrast -- the
        conflict target works here and fails above, which is what makes the extra
        constraint the problem rather than the insert.
        """
        from sqlalchemy import select

        from app.models.commit import Commit
        from tests.factories import make_repo, make_user

        user = await make_user(db_session)
        repo = await make_repo(db_session, user)

        await self.insert_like_ingestion(db_session, [self.commit_row(repo.id)])
        await self.insert_like_ingestion(db_session, [self.commit_row(repo.id)])

        stored = await db_session.execute(select(Commit).where(Commit.repository_id == repo.id))
        assert len(stored.scalars().all()) == 1


class TestAutoUpdateDefaults:
    """
    ``server_default`` populates a column only on rows inserted *after* the
    column lands; existing rows are backfilled by the migration. A column that
    is NULL on a freshly-inserted row -- because nothing in the migration
    asserted ``NOT NULL`` -- breaks the sync task the next time it claims the
    repo: ``next_sync_at IS NULL AND auto_update_enabled`` is a valid filter
    shape, but ``consecutive_sync_failures`` getting NULL breaks every
    arithmetic on it.

    Each row inserted through ``make_repo`` lists every column explicitly (the
    factory was written for a smaller schema), so this is the regression test
    that catches a future migration that adds a NOT NULL column without a
    matching ``server_default`` or backfill.
    """

    async def test_make_repo_yields_a_row_with_non_null_defaults(self, db_session):
        """
        ``make_repo`` builds the row from the factory -- no field-list
        gymnastics, just the model. If the column is NOT NULL on the database
        side and ``server_default`` is set, this passes. If either is missing,
        the INSERT fails or returns a row with NULLs.
        """
        from sqlalchemy import select

        from app.models.repository import Repository
        from tests.factories import make_repo, make_user

        user = await make_user(db_session)
        repo = await make_repo(db_session, user)

        result = await db_session.execute(select(Repository).where(Repository.id == repo.id))
        stored = result.scalar_one()

        assert stored.auto_update_enabled is False
        assert stored.auto_update_interval_hours == 6
        assert stored.next_sync_at is None
        assert stored.last_synced_at is None
        assert stored.sync_status == "idle"
        assert stored.sync_lease_expires_at is None
        assert stored.sync_generation is None
        assert stored.last_sync_error is None
        assert stored.consecutive_sync_failures == 0
        assert stored.last_sync_summary is None
        assert stored.analysis_commit_sha is None

    async def test_inserting_a_row_without_the_new_columns_still_works(self, db_session):
        """
        The reingest path rebuilds ``Repository`` from an explicit field list
        -- a list that, until the migration, did not include the new columns.
        The migration must give every new column a ``server_default`` so this
        INSERT lands a valid row, not a NOT NULL violation.

        The raw INSERT mirrors the shape the application sends: an explicit
        column list with no values for the new ones. ``repo_number`` is supplied
        to dodge the standing repo_number-identity defect -- the column has no
        generator, so any INSERT that omits it raises.
        """
        from sqlalchemy import text

        from tests.factories import make_user

        user = await make_user(db_session)

        # Pick a repo_number this test owns. The factory's counter is local to
        # the module and not exposed, so read it indirectly by inserting a
        # throwaway factory repo first -- which also produces a row we can
        # ignore.
        from tests.factories import make_repo

        throwaway = await make_repo(db_session, user, name="legacy-rebuild-throwaway")
        repo_number = throwaway.repo_number + 1

        await db_session.execute(
            text(
                """
                INSERT INTO repositories
                    (user_id, github_url, name, status, repo_number)
                VALUES
                    (:uid, 'https://github.com/example/legacy-rebuild',
                     'legacy-rebuild', 'pending', :repo_number)
                """
            ),
            {"uid": user.id, "repo_number": repo_number},
        )
        await db_session.flush()

        row = (
            await db_session.execute(
                text(
                    "SELECT auto_update_enabled, auto_update_interval_hours, sync_status, "
                    "consecutive_sync_failures, next_sync_at, sync_lease_expires_at "
                    "FROM repositories WHERE name = 'legacy-rebuild'"
                )
            )
        ).one()
        assert row.auto_update_enabled is False
        assert row.auto_update_interval_hours == 6
        assert row.sync_status == "idle"
        assert row.consecutive_sync_failures == 0
        # Nullable columns stay NULL.
        assert row.next_sync_at is None
        assert row.sync_lease_expires_at is None


def model_schema_diff(metadata=None) -> list:
    """
    Compare the migrated database against the ORM metadata.

    `app.models` is imported for its side effect of registering every mapper; without it
    the metadata would be incomplete and the comparison would report most of the schema
    as "to be removed".
    """
    import app.models  # noqa: F401
    from app.core.database import Base

    engine = create_engine(TEST_SYNC_DB_URL)
    try:
        with engine.connect() as connection:
            context = MigrationContext.configure(connection, opts={"compare_type": True})
            return compare_metadata(context, metadata if metadata is not None else Base.metadata)
    finally:
        engine.dispose()
