"""modify embedding model again

Revision ID: 1c993ad52c53
Revises: b90f023a9981
Create Date: 2026-04-15 20:04:17.844628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c993ad52c53'
down_revision: Union[str, Sequence[str], None] = 'b90f023a9981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('source_type', sa.Enum('symbol', 'commit', 'pull_request', 'document', name='source_type', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embeddings', 'source_type')
    # ### end Alembic commands ###
