"""add more cascade on delete

Revision ID: 2ffeeb4ce948
Revises: 8cffbb1cf735
Create Date: 2026-04-09 21:21:06.998584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ffeeb4ce948'
down_revision: Union[str, Sequence[str], None] = '8cffbb1cf735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('dependencies_target_symbol_id_fkey'), 'dependencies', type_='foreignkey')
    op.create_foreign_key(None, 'dependencies', 'ast_symbols', ['target_symbol_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('embeddings_symbol_id_fkey'), 'embeddings', type_='foreignkey')
    op.drop_constraint(op.f('embeddings_file_id_fkey'), 'embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'embeddings', 'ast_symbols', ['symbol_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'embeddings', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('health_metrics_file_id_fkey'), 'health_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'health_metrics', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'health_metrics', type_='foreignkey')
    op.create_foreign_key(op.f('health_metrics_file_id_fkey'), 'health_metrics', 'files', ['file_id'], ['id'])
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('embeddings_file_id_fkey'), 'embeddings', 'files', ['file_id'], ['id'])
    op.create_foreign_key(op.f('embeddings_symbol_id_fkey'), 'embeddings', 'ast_symbols', ['symbol_id'], ['id'])
    op.drop_constraint(None, 'dependencies', type_='foreignkey')
    op.create_foreign_key(op.f('dependencies_target_symbol_id_fkey'), 'dependencies', 'ast_symbols', ['target_symbol_id'], ['id'])
    # ### end Alembic commands ###
