"""add auth

Revision ID: 3d6ee06b4ec6
Revises: 2ffeeb4ce948
Create Date: 2026-04-10 16:41:36.599689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6ee06b4ec6'
down_revision: Union[str, Sequence[str], None] = '2ffeeb4ce948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repositories', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.drop_constraint(op.f('users_github_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'username')
    op.drop_column('users', 'github_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_github_id_key'), 'users', ['github_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.drop_column('users', 'name')
    op.alter_column('repositories', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
