"""add changed_files_list

Revision ID: 4a3abf082a58
Revises: 005c608e801e
Create Date: 2026-05-31 16:25:05.937774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a3abf082a58'
down_revision: Union[str, Sequence[str], None] = '005c608e801e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commits', sa.Column('changed_files_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commits', 'changed_files_list')
    # ### end Alembic commands ###
