"""add more unique constraints

Revision ID: 570a9dabb547
Revises: e5f221c31fc2
Create Date: 2026-04-15 18:50:21.899270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570a9dabb547'
down_revision: Union[str, Sequence[str], None] = 'e5f221c31fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'code_owners', ['file_id'])
    op.create_unique_constraint(None, 'commits', ['hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commits', type_='unique')
    op.drop_constraint(None, 'code_owners', type_='unique')
    # ### end Alembic commands ###
