"""update brief type

Revision ID: 650508da1616
Revises: 1c993ad52c53
Create Date: 2026-04-16 21:37:45.570071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '650508da1616'
down_revision: Union[str, Sequence[str], None] = '1c993ad52c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE onboarding_guides ALTER COLUMN architecture_brief TYPE jsonb USING architecture_brief::jsonb"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('onboarding_guides', 'architecture_brief',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
