"""add cascade deletes

Revision ID: 6a7706111825
Revises: 8d8c3934e9f4
Create Date: 2026-04-18 00:02:55.967292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7706111825'
down_revision: Union[str, Sequence[str], None] = '8d8c3934e9f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('code_owners_file_id_fkey'), 'code_owners', type_='foreignkey')
    op.create_foreign_key(None, 'code_owners', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('commits_repository_id_fkey'), 'commits', type_='foreignkey')
    op.create_foreign_key(None, 'commits', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('glossary_entries_symbol_id_fkey'), 'glossary_entries', type_='foreignkey')
    op.drop_constraint(op.f('glossary_entries_repository_id_fkey'), 'glossary_entries', type_='foreignkey')
    op.create_foreign_key(None, 'glossary_entries', 'ast_symbols', ['symbol_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'glossary_entries', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('onboarding_guides_repository_id_fkey'), 'onboarding_guides', type_='foreignkey')
    op.create_foreign_key(None, 'onboarding_guides', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('pull_requests_repository_id_fkey'), 'pull_requests', type_='foreignkey')
    op.create_foreign_key(None, 'pull_requests', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('repositories_user_id_fkey'), 'repositories', type_='foreignkey')
    op.create_foreign_key(None, 'repositories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.create_foreign_key(op.f('repositories_user_id_fkey'), 'repositories', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'pull_requests', type_='foreignkey')
    op.create_foreign_key(op.f('pull_requests_repository_id_fkey'), 'pull_requests', 'repositories', ['repository_id'], ['id'])
    op.drop_constraint(None, 'onboarding_guides', type_='foreignkey')
    op.create_foreign_key(op.f('onboarding_guides_repository_id_fkey'), 'onboarding_guides', 'repositories', ['repository_id'], ['id'])
    op.drop_constraint(None, 'glossary_entries', type_='foreignkey')
    op.drop_constraint(None, 'glossary_entries', type_='foreignkey')
    op.create_foreign_key(op.f('glossary_entries_repository_id_fkey'), 'glossary_entries', 'repositories', ['repository_id'], ['id'])
    op.create_foreign_key(op.f('glossary_entries_symbol_id_fkey'), 'glossary_entries', 'ast_symbols', ['symbol_id'], ['id'])
    op.drop_constraint(None, 'commits', type_='foreignkey')
    op.create_foreign_key(op.f('commits_repository_id_fkey'), 'commits', 'repositories', ['repository_id'], ['id'])
    op.drop_constraint(None, 'code_owners', type_='foreignkey')
    op.create_foreign_key(op.f('code_owners_file_id_fkey'), 'code_owners', 'files', ['file_id'], ['id'])
    # ### end Alembic commands ###
