"""add cascade on delete

Revision ID: 8cffbb1cf735
Revises: ec40440330d3
Create Date: 2026-04-09 21:14:16.518712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cffbb1cf735'
down_revision: Union[str, Sequence[str], None] = 'ec40440330d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ast_symbols_file_id_fkey'), 'ast_symbols', type_='foreignkey')
    op.create_foreign_key(None, 'ast_symbols', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('dependencies_source_symbol_id_fkey'), 'dependencies', type_='foreignkey')
    op.create_foreign_key(None, 'dependencies', 'ast_symbols', ['source_symbol_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('embeddings_embedding_idx'), table_name='embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_constraint(op.f('embeddings_repository_id_fkey'), 'embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'embeddings', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('files_repository_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('health_metrics_repository_id_fkey'), 'health_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'health_metrics', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'health_metrics', type_='foreignkey')
    op.create_foreign_key(op.f('health_metrics_repository_id_fkey'), 'health_metrics', 'repositories', ['repository_id'], ['id'])
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key(op.f('files_repository_id_fkey'), 'files', 'repositories', ['repository_id'], ['id'])
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('embeddings_repository_id_fkey'), 'embeddings', 'repositories', ['repository_id'], ['id'])
    op.create_index(op.f('embeddings_embedding_idx'), 'embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_constraint(None, 'dependencies', type_='foreignkey')
    op.create_foreign_key(op.f('dependencies_source_symbol_id_fkey'), 'dependencies', 'ast_symbols', ['source_symbol_id'], ['id'])
    op.drop_constraint(None, 'ast_symbols', type_='foreignkey')
    op.create_foreign_key(op.f('ast_symbols_file_id_fkey'), 'ast_symbols', 'files', ['file_id'], ['id'])
    # ### end Alembic commands ###
