"""modify and add more schemas

Revision ID: aff92caa271e
Revises: 3d6ee06b4ec6
Create Date: 2026-04-15 08:51:32.331320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aff92caa271e'
down_revision: Union[str, Sequence[str], None] = '3d6ee06b4ec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('author_email', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('authored_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_guides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('reading_order', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('critical_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('architecture_brief', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id')
    )
    op.create_table('pull_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('reviewers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_owners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('primary_owner', sa.String(), nullable=True),
    sa.Column('contributors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bus_factor', sa.Integer(), nullable=False),
    sa.Column('is_knowledge_silo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glossary_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['ast_symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ast_symbols', sa.Column('docstring', sa.Text(), nullable=True))
    op.add_column('ast_symbols', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('ast_symbols', 'metadata')
    op.drop_column('dependencies', 'metadata')
    op.add_column('embeddings', sa.Column('source_id', sa.UUID(), nullable=True))
    op.add_column('embeddings', sa.Column('source_type', sa.String(), nullable=False))
    op.alter_column('embeddings', 'file_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('embeddings_symbol_id_fkey'), 'embeddings', type_='foreignkey')
    op.drop_column('embeddings', 'symbol_id')
    op.drop_column('embeddings', 'metadata')
    op.add_column('files', sa.Column('fan_in', sa.Integer(), nullable=False))
    op.add_column('files', sa.Column('fan_out', sa.Integer(), nullable=False))
    op.add_column('files', sa.Column('criticality', sa.String(), nullable=True))
    op.add_column('files', sa.Column('criticality_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('files', sa.Column('change_frequency', sa.Float(), nullable=True))
    op.add_column('files', sa.Column('has_tests', sa.Boolean(), nullable=False))
    op.alter_column('files', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('health_metrics', 'computed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('repositories', sa.Column('repo_number', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('repositories', sa.Column('detected_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('repositories', sa.Column('entry_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('repositories', sa.Column('architecture_summary', sa.Text(), nullable=True))
    op.alter_column('repositories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('repositories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'repositories', ['repo_number'])
    op.drop_column('repositories', 'metadata')
    op.alter_column('users', 'github_access_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'github_access_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('repositories', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'repositories', type_='unique')
    op.alter_column('repositories', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('repositories', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('repositories', 'architecture_summary')
    op.drop_column('repositories', 'entry_points')
    op.drop_column('repositories', 'detected_stack')
    op.drop_column('repositories', 'repo_number')
    op.alter_column('health_metrics', 'computed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('files', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('files', 'has_tests')
    op.drop_column('files', 'change_frequency')
    op.drop_column('files', 'criticality_reasons')
    op.drop_column('files', 'criticality')
    op.drop_column('files', 'fan_out')
    op.drop_column('files', 'fan_in')
    op.add_column('embeddings', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('embeddings', sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('embeddings_symbol_id_fkey'), 'embeddings', 'ast_symbols', ['symbol_id'], ['id'], ondelete='CASCADE')
    op.alter_column('embeddings', 'file_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('embeddings', 'source_type')
    op.drop_column('embeddings', 'source_id')
    op.add_column('dependencies', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ast_symbols', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('ast_symbols', 'created_at')
    op.drop_column('ast_symbols', 'docstring')
    op.drop_table('glossary_entries')
    op.drop_table('code_owners')
    op.drop_table('pull_requests')
    op.drop_table('onboarding_guides')
    op.drop_table('commits')
    # ### end Alembic commands ###
