"""add_ingested_version_fields

Revision ID: b4e7be529e5b
Revises: 1882dcee3456
Create Date: 2026-06-23 07:01:51.126856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e7be529e5b'
down_revision: Union[str, Sequence[str], None] = '1882dcee3456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('ingested_branch', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('ingested_commit_sha', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'ingested_commit_sha')
    op.drop_column('repositories', 'ingested_branch')
    # ### end Alembic commands ###
