"""modify embedding model

Revision ID: b90f023a9981
Revises: e8dffd71f0da
Create Date: 2026-04-15 20:01:35.167154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90f023a9981'
down_revision: Union[str, Sequence[str], None] = 'e8dffd71f0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embeddings', 'source_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('embeddings', 'source_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('source_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('embeddings', 'source_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
