"""give repo_number an identity generator

Revision ID: d4e5f6a7b8c9
Revises: c3d4e5f6a7b8
Create Date: 2026-10-02 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4e5f6a7b8c9"
down_revision: Union[str, Sequence[str], None] = "c3d4e5f6a7b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Give ``repositories.repo_number`` the generator the model always declared.

    ``aff92caa271e`` added the column as a plain ``integer NOT NULL``: the
    ``autoincrement=True`` it passed is inert on a non-primary-key
    ``ADD COLUMN``, so no sequence was ever created. The revision meant to
    convert it was left empty, which is why a database built from these
    migrations could not create a repository at all.

    The guard is deliberately "neither an identity nor a default": a database
    that was patched by hand has a working generator already -- production
    carries ``DEFAULT nextval('repositories_repo_number_seq')`` -- and ``ADD
    GENERATED`` refuses to run on a column that already has a default. Those
    databases are left exactly as they are; everything else gets the identity.
    """
    conn = op.get_bind()
    attidentity, atthasdef = conn.execute(
        sa.text(
            """
            SELECT attidentity, atthasdef
            FROM pg_attribute
            WHERE attrelid = 'public.repositories'::regclass
              AND attname = 'repo_number'
            """
        )
    ).one()

    if attidentity or atthasdef:
        return

    op.execute(
        "ALTER TABLE repositories "
        "ALTER COLUMN repo_number ADD GENERATED BY DEFAULT AS IDENTITY"
    )
    # Adding an identity to a column that already holds rows starts the
    # sequence at 1, so the next insert would collide with an existing row.
    # Seed it immediately past the current maximum; on an empty table this
    # evaluates to 1, which is also the right starting point.
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('repositories', 'repo_number'),
            COALESCE((SELECT MAX(repo_number) FROM repositories), 0) + 1,
            false
        );
        """
    )


def downgrade() -> None:
    """Return ``repo_number`` to a plain ``integer NOT NULL`` column.

    Dropping the identity drops its sequence. Existing values and the unique
    constraint are untouched, so the column is exactly what ``aff92caa271e``
    left behind.
    """
    op.execute("ALTER TABLE repositories ALTER COLUMN repo_number DROP IDENTITY IF EXISTS")
