"""add unique constraints

Revision ID: e5f221c31fc2
Revises: aff92caa271e
Create Date: 2026-04-15 18:42:53.640130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f221c31fc2'
down_revision: Union[str, Sequence[str], None] = 'aff92caa271e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_commit_repo_hash', 'commits', ['repository_id', 'hash'])
    op.create_unique_constraint('uq_pr_repo_number', 'pull_requests', ['repository_id', 'number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_pr_repo_number', 'pull_requests', type_='unique')
    op.drop_constraint('uq_commit_repo_hash', 'commits', type_='unique')
    # ### end Alembic commands ###
