"""add git_last_modified to files

Revision ID: e8dffd71f0da
Revises: 570a9dabb547
Create Date: 2026-04-15 19:31:06.474437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8dffd71f0da'
down_revision: Union[str, Sequence[str], None] = '570a9dabb547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('git_last_modified', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'git_last_modified')
    # ### end Alembic commands ###
